server:
 port: 8050
spring:
  application:
    name: account
  datasource:
    driver-class-name=com: com.mysql.jdbc.Driver
    name: user
    url: jdbc:mysql://localhost:3306/light?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
    type-aliases-package: com.gateway