server:
 port: 8050
spring:
  application:
    name: account
  datasource:
    name: user
    url: jdbc:mysql://127.0.0.1:3306/light?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
    type-aliases-package: com.gateway