server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: nettyclient
  routes:
    nettyclient:
     serviceId: nettyclient
     path: /nettyclient/**
     sensitiveHeaders: "*"
    account:
     seviceId: account
     path: /user/**
     sensitiveHeaders: "*"